---
name: Codespell

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@de089481bd65b71b4d02e34ffb3566b6d189333e
